export const NOTIFICATION_SUB_CATEGORIES = {
    LOGIN_SUCCEED: 111,
    LOGIN_FAILED: 112,
    TICKET_USER_REGISTERED: 211,
    TICKET_ADMINISTRATOR_REGISTERED: 212,
    TICKET_THREAD_USER_REGISTERED: 213,
    TICKET_THREAD_ADMINISTRATOR_REGISTERED: 214,
};
